- bin/savepdf
- lib/preview.js
- lib/save.js
Since the problem discussed in GoogleChrome/lighthouse#2726 and GoogleChrome/chrome-launcher#6, on the certain UNIX systems fail to launch Chrome and throw ECONNREFUSED error.
The problem is solved by adding `--no-sandbox` option to chrome-launcher, but it is a dangerous work-around and I didn't want to add this option by default.
This fix add `--no-sandbox` option to savepdf, to enable Chrome launching without Sandbox.
> Add --no-sandbox option to launch chrome on unix systems

- lib/misc.js
- support to flattened node_modules
- for yarn and new npm
- vivliostyle and others, it was 404.
- change listen address
- displayed as `Launching source server... http://localhost:13000`, it is actually published at 0.0.0.0.
> support to flattened node_modules / change listen address

- broker/main.js
- src/lib/build.ts
- src/lib/misc.ts
- tsconfig.json
Fixes #14.
The broker defaults to auto mode, which follows the viewport size. Chrome does not resize the viewport when printing, so Vivliostyle will not re-render. Chrome will instead try to fit the viewport inside the selected paper size, leading to it switching to landscape every time because of the `--window-size` parameter.
Instead, pass the paper size from the CLI to configure both the render size and the `@page size` directive, which in turn effects the paper size when printing. This saves us from having to worry about the viewport or calculate inch sizes ourselves: the browser and vivliostyle core handle all of it, so the parsing gets simpler.
Example output of portrait Letter outputting correctly: [output.pdf](https://github.com/vivliostyle/vivliostyle-cli/files/4023279/output.pdf) …
> Require broker to render using the size passed in from the CLI

- package.json
The current Node.js Active LTS is v10, so we will use that as the lower limit.
> Explicit support for Node.js version

- jest.config.js
- package.json
- src/lib/broker.d.ts
- src/lib/build.ts
- src/lib/postprocess.ts
- src/lib/util.ts
- tests/cli.test.ts
- tests/fixtures/node.js
- tests/fixtures/wood/index.html
- tsconfig.json
- yarn.lock
Adds postprocessing of the PDF to copy in the metadata and table of contents from the source document, as parsed by Vivliostyle Core.
The metadata copies over the Title, Author, Subject, Keywords, Creator, Language, and Creation Date from the source document, if provided. If not provided, Creator will be “Chromium”, which Chromium puts there. The Producer is set to “Vivliostyle”.
The PDF outline will match the structure of the source document’s TOC, including deep destination links.
The metadata and TOC use linked functionality in Vivliostyle, so this PR is paired with vivliostyle/vivliostyle.js#634. If the functionality is not in Vivliostyle, vivliostyle-cli will function as before; it will not break.
> Add metadata and outline to PDF

- src/lib/postprocess.ts
PDF Bookmarks (outline) are now generated thanks to the PR #47 "Add metadata and outline to PDF".
But it causes "Error: Cannot read property 'length' of undefined" when TOC is not available.
Note: TOC (items) is generated in Vivliostyle Core only when Book mode is used and TOC element exists in the book.
So this fix is needed.
> fix: build error when TOC is not available

- package.json
- src/builder.ts
- src/cli.ts
- src/commands/build.ts
- src/commands/init.ts
- src/commands/preview.ts
- src/config.ts
- src/pdf.ts
- src/postprocess.ts
- src/server.ts
- src/util.ts
- tests/cli.test.ts
- yarn.lock
On Windows, with Node.js `path` module,  `path.join()`, `path.relative()`, etc. functions return path strings containing backslashes as directory separator.
Path string with backslashes cannot be used where URL path is required (e.g. `href` in `manifest.json`), and cannot be used with [globby](https://www.npmjs.com/package/globby). So this problem causes [errors on Windows](https://github.com/vivliostyle/vivliostyle-cli/issues/68).
Using [`upath`](https://www.npmjs.com/package/upath) instead of normal `path` solves the problem.
Fixes #68
> fix: Errors due to path problem on Windows

- package.json
- yarn.lock
FIxes #81
This PR update @vivliostyle/core to the specific version (2.1.4). This ensures us to use the same Vivliostyle version.
> chore: Update core version

- src/commands/init.ts
- tests/init.test.ts
add test for init command.
オプション指定の順番の関係で、initコマンドの--language,--size,--themeを指定しても生成されるvivliosyle.config.jsに反映されない不具合を修正しました。
また、initコマンドに関するテストケースを作成しました。
> fix: --language,--size, --theme options for init command is not working.

- package.json
- src/builder.ts
- yarn.lock
Windowsではpath.relativeで付与されるセパレータが&lt;a href="\.\.&yen;test.html"&gt;のように"&yen;"になるためテストに失敗します。
生成されたtoc.htmlをMacにコピーしてChromeで試した限りでは"/"でも"&yen;"でも区切りとして機能しているようなのでテストで引っ掛るところ以外は修正しなくても実用上は問題ないと思います。
import path form 'upath'; の順番が変わってしまったのはpretty-quickによる自動フォーマットの結果です。
> fix: toc test fails due to separator on Windows

- src/util.ts
JESTでテストを実行した際にエラーが発生しても、スタックトレースで表示されるのはテストケースの失敗までなのでどこでエラーが発生したかが判断しにくくなっています。
gracefulError関数でエラー発生時点のスタックトレースを表示することで障害箇所を見付けやすくなります。
一応verbose変数で表示をON/OFFできるようにしていますが、個人的には常時ONでも良いと思います。
> feat: display stacktrace on error

- src/pdf.ts
This PR removes a deprecated `waitFor` function. [The `waitForFunction` is equivalent to that](https://github.com/puppeteer/puppeteer/issues/6214).
> chore: Remove deprecated waitFor function

- src/config.ts
- src/input.ts
- src/server.ts
- tests/__snapshots__/config.test.ts.snap
- tests/config.test.ts
まだ叩き台レベルですが、とりあえず以下のコマンドを実行してプレビューできるところまで実装しました。
```
vivliostyle preview https://vivliostyle.github.io/vivliostyle_doc/ja/vivliostyle-user-group-vol1/
```
しかし、buildすると以下のようなエラーが発生します。
また、生成されたPDFを見るとレイアウト崩れが発生しています。(脚注に次のページの先頭が食い込んでいる)
```
% vivliostyle build https://vivliostyle.github.io/vivliostyle_doc/ja/vivliostyle-user-group-vol1/                                                                                                                       (git)-[develop]
✖ 404 https://vivliostyle.github.io/vivliostyle_doc/ja/vivliostyle-user-group-vol1/assets/fonts/SourceHanSerifJP/SourceHanSerifJP-Regular.otf
✖ 404 https://vivliostyle.github.io/vivliostyle_doc/ja/vivliostyle-user-group-vol1/assets/fonts/SourceHanSerifJP/SourceHanSerifJP-SemiBold.otf
``` …
> fix: Can't load from Web URL

- examples/theme-preset/vivliostyle.config.js
README.mdには、
```
-s, --size <size>             output pdf size [Letter]
preset: A5, A4, A3, B5, B4, JIS-B5, JIS-B4, letter, legal, ledger
custom(comma separated): 182mm,257mm or 8.5in,11in
```
とありますが、同梱のexamples/theme-preset内のvivliostyle.config.jsでは
```
size: 'JIS-B6',
```
のように存在しないサイズ指定になっています。
このままbuildするとA5サイズのpdfが出力されます。
試しにJIS-B6にするためにsize: '128mm,182mm' と指定したところレイアウトが崩れてしまいました。
size: 'A5' に変更したほうが良いのではないでしょうか。
> fix: exmaples/theme-preset size(JIS-B6 -> A5)

- src/commands/preview.ts
- src/pdf.ts
Chromiumの起動オプションに `--disable-web-security` を加えることで、CORS制限のためにWebの文書の組版ができなかった問題を解決します。
テスト
```
vivliostyle preview https://example.com
```
修正前:
修正後:
> fix: Failed to load from web because of CORS error

- src/builder.ts
- src/commands/build.ts
- src/commands/init.ts
- src/commands/preview.ts
- src/config.ts
- src/util.ts
Fixes the following problems:
- On Windows, `process.cwd()` returns Windows path containing backslashes
and it causes problem when matching with `startsWith()` to other paths
that are normalized using forward slashes.
- When config file is not used, `workspaceDir` and `entryContextDir` are
set to the directory containing the input file. In this condition,
file changes inside that directory (`p.startsWith(config.workspaceDir)`)
are ignored, but file changes in the current directory are watched.
This is contrary to the expected behavior.
- XHTML, EPUB (.epub or .opf), pub-manifest (.json) input are ignored.
> fix: Preview watch not working as expected

- src/commands/preview.ts
This is a follow-up fix of https://github.com/vivliostyle/vivliostyle-cli/pull/149.
> fix: Preview watch not refreshed when CSS file is changed

- src/commands/build.parser.ts
- src/commands/build.ts
- src/commands/preview.parser.ts
- src/commands/preview.ts
- src/config.ts
- src/pdf.ts
- src/server.ts
- src/util.ts
- tests/__snapshots__/config.test.ts.snap
- tests/broker.test.ts
- tests/config.test.ts
Resolves #112
New CLI options:
```
--style <stylesheet>            additional stylesheet URL or path
--user-style <user_stylesheet>  user stylesheet URL or path
```
These options are passed to the vivliostyle-viewer `style` and `userStyle` parameters.
Note:
- `--style` is to add an [author stylesheet](https://developer.mozilla.org/en-US/docs/Web/CSS/Cascade#author_stylesheets),
and `--user-style` is to set a [user stylesheet](https://developer.mozilla.org/en-US/docs/Web/CSS/Cascade#user_stylesheets).
- The stylesheet URL can be a data URL, e.g., `data:,@page{margin:0}body{margin:0}`.
- A relative path is resolved relative to the current working directory.
With this update, URL tests using `/^https?:\/\//.test(str)` are replaced to `isUrlString(str)`,
which tests …
> feat: Add additional/user stylesheet options

- src/builder.ts
- src/html.ts
Fixes #155
publication.json と 目次 HTML に url として渡されるパスを `encodeURI()` でエンコードするようにしました。
> fix: Non-ASCII directory/file is not available. Error: Validation of pubManifest failed

- CHANGELOG.md
- package.json
- src/builder.ts
- src/commands/init.ts
- src/config.ts
- src/schema/vivliostyle.config.d.ts
- src/schema/vivliostyle.config.schema.json
- tests/__snapshots__/config.test.ts.snap
- tests/builder.test.ts
- tests/fixtures/builder/manuscript/soda.md
- tests/fixtures/builder/vfm.config.js
- tests/fixtures/config/vivliostyle.config.valid.1.js
resolve #171 
```js
module.exports = {
language: 'en',
theme: 'theme_print.css',
entry: [
'example/Alice.md',
],
hardLineBreaks: true,
disableFormatHtml: true,
}
```
のように、vivliostyle.config.js 内で hardLineBreaks と disableFormatHtml オプションを指定できるようにしました。CLI のオプションとしては未実装です。
> feat: add VFM options (hardLineBreaks, disableFormatHtml) to vivliostyle.config.js

- src/commands/preview.ts
- src/config.ts
vivliostyle.config.js を更新した際にもpreviewをリロードします。
-c オプションでconfigファイルを指定した場合にも対応します。
ただし、監視対象のディレクトリの外にconfigファイルがある場合は対応できません。
ファイル名のみでチェックしているため監視対象ディレクトリ内の別ディレクトリの同名ファイルを変更した場合にもリロードしてしまいますが、レアケースですし致命的な問題にもならないと思いますので対応していません。
> feat: vivliostyle-preview reload when vivliostyle.config.js updated

- src/pdf.ts
This fix the problem explained in https://github.com/vivliostyle/vivliostyle-cli/issues/214#issuecomment-924811171
Fixes #214
> fix: TypeError: Cannot read properties of null (reading 'getMetadata')

- package.json
- yarn.lock
https://github.com/vivliostyle/vivliostyle.js/releases/tag/v2.13.0
- "The target resource is invalid" error caused by TOC with non-HTML links
- CSS parser error, failed to parse stylesheet
- Layout problem with Web fonts
- Pseudo elements should not be generated when content is none
- Viewer page position should be kept after the heading ID changed
- Allow JavaScript in HTML documents
- **viewer:** Add zoom URL parameter to keep zoom value on reloading
> feat: Update Vivliostyle.js to 2.13.0: Allow JavaScript in documents, etc.

- src/build.ts
- src/cli.ts
- src/commands/build.parser.ts
- src/commands/build.ts
- src/commands/init.parser.ts
- src/commands/init.ts
- src/commands/preview.parser.ts
- src/commands/preview.ts
- src/index.ts
- src/init.ts
- src/pdf.ts
- src/preview.ts
- tests/api.test.ts
This PR fixes using the named exports `build` and `preview` by other packages. For completeness, it also adds `init`. A test is added for using `build` this way.
The exports were first made available in #52. They were broken after #96, because the subcommands ran their parsing at the top level of the file. Just importing the methods would run the command parser and exit the process, ignoring the arguments passed in.
The named exports `build`, `preview`, and `init` are moved to separate files. The new files specifically don’t import `commander` so that they work with tree-shaking tools.
> Re-enable using commands as api

- package.json
- yarn.lock
- https://github.com/vivliostyle/vivliostyle.js/releases/tag/v2.14.1
- https://github.com/vivliostyle/vivliostyle.js/releases/tag/v2.14.0
- support CSS text-spacing and hanging-punctuation in generated content
- support the allow-end value of text-spacing and hanging-punctuation
- text-spacing not working depending on fonts
- CSS text-orientation property was ignored in page margin boxes
- do not ignore metadata (language, author) in publication manifest
- follow-up fix to text-spacing and hanging-punctuation support
- overflow:hidden should not be default in page margin boxes
- page margin boxes with vertical writing-mode not properly aligned
- TypeError occurred with TOC button when the book url has fragment
- Unnecessary aria-hidden attributes caused tagged PDF output broken
> feat: Update Vivliostyle.js to 2.14.1: Improved text-spacing support

- package.json
- yarn.lock
- https://github.com/vivliostyle/vivliostyle.js/releases/tag/v2.14.2
- footnotes not positioned correctly in vertical writing mode
- hang-up with footnote/pagefloat and ::after pseudo element
- margin-block-end on page floats ignored in vertical writing mode
- should generate single text node for pseudo elements if possible
- use appropriate fallback page size when window size is not available
- wrong indent of fullwidth opening punctuation at first line in second page
> fix: Update Vivliostyle.js to 2.14.2: bug fixes

- package.json
- yarn.lock
https://github.com/puppeteer/puppeteer/blob/main/CHANGELOG.md
> - **chromium:** roll to Chromium 99.0.4844.16 (r961656)
> feat: Update Puppeteer-core to 13.3.1 (Chromium 99)

- package.json
- yarn.lock
https://github.com/vivliostyle/vivliostyle.js/releases/tag/v2.14.3
- internal links broken in output PDF
- should not link to blank page generated by a spread break
- hanging-punctuation not working properly with non-full-width punctuation
----
- Fix https://github.com/vivliostyle/vivliostyle-cli/issues/253
> fix: Update Vivliostyle.js to 2.14.3: Fix bugs on links in output PDF

- package.json
- yarn.lock
https://github.com/vivliostyle/vivliostyle.js/releases/tag/v2.14.4
- wrong page break with ruby at beginning of a paragraph
- **viewer:** tweak mouse wheel/scroll handling to prevent unexpected page moves
> fix: Update Vivliostyle.js to 2.14.4: Fix wrong page break with ruby

- README.md
- src/commands/build.parser.ts
--timeout のデフォルト値が "[60s]" と記述されてました：
```
-t, --timeout <seconds>          timeout limit for waiting Vivliostyle process [60s]
```
しかし、ソースコードを見ると、120秒となっています。
また、"[60s]" と書かれてますが、単位 "s" を付けると無効になります。
次のように、"[120]" という記述に修正しました：
```
-t, --timeout <seconds>          timeout limit for waiting Vivliostyle process [120]
```
> docs: correct --timeout default value

- src/commands/build.ts
- fix #269
This fixes the problem that the build process is not terminated in docker mode (`--render-mode=docker`).
The problem was caused by the change that `process.exit(0);` was removed from the `build()` function (commit https://github.com/vivliostyle/vivliostyle-cli/pull/243/commits/bed618317584bb280484544931c380cc3e3e2e86 "fix: importing command api causes process exit"), so this fix adds `process.exit(0);` in the `.then(…)` after the `build()` function call in `commands/build.ts`.
> fix: Process not terminated in docker mode

- package.json
- yarn.lock
https://github.com/vivliostyle/vivliostyle.js/releases/tag/v2.14.6
- Fallback page size not applied on HeadlessChrome on Linux or Windows
- Page float displayed unexpectedly in earlier page when target-counter is used
- TypeError: Cannot read properties of null
- Web fonts (with JavaScript) not enabled when used in the middle of large HTML file
> fix: Update Vivliostyle.js to 2.14.6: Bug Fixes

- package.json
- yarn.lock
I tested this (puppeteer-core 13.6.0 with Chromium 101)) and found that the problem ("What's new in Chrome" tab on preview) was resolved.
- https://github.com/vivliostyle/vivliostyle-cli/issues/248
> feat: Update Puppeteer-core to 13.6.0 (Chromium 101)

- package.json
- yarn.lock
The `--headless=chrome` mode may solve issues existed in chromium headless mode.
> feat: Update Puppeteer-core to 13.7.0: support chrome headless mode

- package.json
- yarn.lock
https://github.com/vivliostyle/vivliostyle.js/releases/tag/v2.15.0
- crop marks color should not be C0 M0 Y0 K100 when converted to CMYK
- text-spacing causes text accessibility problem in output PDF
- Add crop-offset property for at-page rule
- Support printing mixed page sizes
> feat: Update Vivliostyle.js to 2.15.0: Improve printing support

- package.json
- yarn.lock
https://github.com/vivliostyle/vivliostyle.js/releases/tag/v2.15.2
- showTOC() takes a long time on large HTML document
- This also fixes https://github.com/vivliostyle/vivliostyle-cli/issues/285
- first-letter pseudo element with float disappears when page break occurs in the parent paragraph
- SyntaxError ':not(:not(script, link, style) ~ \*)' is not a valid selector in slightly older browsers
- Flexbox layout broken due to text-spacing side-effect
- hanging-punctuation/text-spacing not working correctly when a ruby element is adjacent
- wrong hanging-punctuation on half-width ideographic comma/fullstop
> fix: Update Vivliostyle.js to 2.15.2: Bug Fixes

- src/preview.ts
The chokidar.watch() option `ignoreInitial` must be set to true to prevent unnecessary change event
that causes wrong "Built _file name_" message and unnecessary reloading on preview.
- fix #284
> fix: wrong "Built …" message and unnecessary reloading on preview

- package.json
- yarn.lock
https://github.com/vivliostyle/vivliostyle.js/releases/tag/v2.15.3
- break-after:avoid on heading not honored when float exists after the heading
- Error F_TASK_NOT_TOP_FRAME occurs when resizing and reformatting pages
- page content missing in PDF output when bleed is specified without marks
> fix: Update Vivliostyle.js to 2.15.3: Bug Fixes

- package.json
- yarn.lock
https://github.com/vivliostyle/vfm/releases/tag/v1.2.2
* remove heading attributes notation on page title ([f23ff1f](https://github.com/vivliostyle/vfm/commit/f23ff1f5182b0554f73f0fe92ee3a068e7aab2a1))
* Type error of object property ([e8755d9](https://github.com/vivliostyle/vfm/commit/e8755d9de0839878b018a1b2c6f5b84c4ba93416))
> fix: Update VFM to 1.2.2

- src/browser.ts
This solves the problem of inconsistent layout between viewing and printing.
About the --enable-blink-features=LayoutNGPrinting switch, see
https://bugs.chromium.org/p/chromium/issues/detail?id=1121942#c79
> feat: Set chromium option --enable-blink-features=LayoutNGPrinting

- .github/workflows/cd-workflow.yml
- .github/workflows/test.yml
- Dockerfile
Before this change, the size of Docker image ghcr.io/vivliostyle/cli:5.1.0 was 2.12GB,
and with this change, it is reduced to 1.55GB.
- resolves #305
> fix: Reduce size of Docker image

- Dockerfile
- remove poor quality fonts (Unifont, IPAGothic, WenQuanYiZenHei)
- install Microsoft TrueType core fonts (Andale Mono, Arial, Arial Black, Comic Sans MS, Courier New, Georgia, Impact, Times New Roman, Trebuchet MS, Verdana, and Webdings)
- install all Noto fonts (including Noto CJK fonts, such as "Noto Serif CJK JP" and "Noto Sans CJK JP")
- font alias Win/Mac mincho and gothic font names to Noto CJK fonts ("Yu Mincho" → "Noto Serif CJK JP", "Hiragino Sans" → "Noto Sans CJK JP", etc)
---
- resolves #303
> feat: Improve font configuration in the docker image

- package.json
- yarn.lock
https://github.com/vivliostyle/vivliostyle.js/releases/tag/v2.15.6
- Remove workaround for Chromium legacy layout engine
- Error handling of negative or zero page area size that causes endless page generation loop
> fix: Update Vivliostyle.js to 2.15.6: fix to use Chromium LayoutNG

- package.json
- yarn.lock
https://github.com/vivliostyle/vivliostyle.js/releases/tag/v2.15.7
- float:left/right positioning broken on printing via Vivliostyle CLI v5.2.1
> fix: Update Vivliostyle.js to 2.15.7: Fix float layout on printing

- package.json
- yarn.lock
https://github.com/vivliostyle/vivliostyle.js/releases/tag/v2.15.8
- Bleed not working when bleed is specified but marks and crop-offset are unspecified
- Bottom border at page bottom edge disappeared on printing via Vivliostyle CLI v5.2.3
- Error: Negative or zero page area size
> fix: Update Vivliostyle.js to 2.15.8: Bug Fixes

- package.json
- yarn.lock
https://github.com/vivliostyle/vivliostyle.js/releases/tag/v2.16.0
- Content overflow caused by line breaks in table cells that are not present in preview and appear in print
- CSS explicit defaulting (e.g. all: unset, break-inside: inherit) may not work as expected
- font-size with rem on root element causes wrong 1em size
- Footnote may disappear on Adaptive Layout
- Add support for CSS 'inset' shorthand
- Add support for CSS property value keywords 'initial', 'unset' and
- Add support for CSS shorthand property
- Improve CSS validator to support new property values supported in browser
> feat: Update Vivliostyle.js to 2.16.0: Improve CSS support

- package.json
- yarn.lock
https://github.com/vivliostyle/vivliostyle.js/releases/tag/v2.17.1
- float with clear not properly positioned
- Relative length units such as em and vw used in CSS calc() not working correctly
- unnecessary warning "Property not supported by the browser: ua-list-item-count"
> fix: Update Vivliostyle.js to 2.17.1: Bug Fixes

- package.json
- yarn.lock
- https://github.com/vivliostyle/vivliostyle.js/releases/tag/v2.18.1
- https://github.com/vivliostyle/vivliostyle.js/releases/tag/v2.18.0
- **viewer:** add crop marks setting ([1d0834b](https://github.com/vivliostyle/vivliostyle.js/commit/1d0834b778f41fcb65553d043d3de30a424a0aea)), closes [#993](https://github.com/vivliostyle/vivliostyle.js/issues/993)
- **viewer:** change "User Style" to "Custom Style" and treat it as an author stylesheet by default ([bdb26d4](https://github.com/vivliostyle/vivliostyle.js/commit/bdb26d474f803eb44c9f09e2489dcda668231396)), closes [#991](https://github.com/vivliostyle/vivliostyle.js/issues/991)
- **viewer:** set bookMode=true as default ([5411264](https://github.com/vivliostyle/vivliostyle.js/commit/5411264648341144997f1d60a44f218a13625b42)), closes …
> feat: Update Vivliostyle.js to 2.18.1: improved viewer settings and bug fixes

- src/preview.ts
- src/server.ts
Vivliostyle Viewer start page has "Input a document URL or HTML code" box and that is useful for testing with HTML+CSS code.
> feat: allow empty input for preview command to open Viewer start page

- src/browser.ts
- src/builder.ts
- src/config.ts
- src/container.ts
- src/pdf.ts
- src/preview.ts
- src/util.ts
- src/webbook.ts
This is important especially on Windows. See issue #325.
- fix #325
> fix: case-insensitive pathname comparison is necessary for Windows

- package.json
- yarn.lock
https://github.com/vivliostyle/vivliostyle.js/releases/edit/v2.18.2
- **viewer:** Apply and Cancel buttons in Settings menu should not be scrolled out ([2df1b74](https://github.com/vivliostyle/vivliostyle.js/commit/2df1b7449dd78ae30c0d3a45a1b90035dcda67c7))
- **viewer:** disable shortcut keys when an input box exists in document and that is activated ([0eedcc0](https://github.com/vivliostyle/vivliostyle.js/commit/0eedcc0510ca862753b0aa6f6474d06a5d4ce8e4))
- wrong text-spacing when non-fullwidth closing and fullwidth opening brackets are adjacent ([331322b](https://github.com/vivliostyle/vivliostyle.js/commit/331322b63b8105e3e73eb53f5d2028b1a2e3efbe)), closes [# 1003](https://github.com/vivliostyle/vivliostyle.js/issues/1003)
- wrong text-spacing with fullwidth punctuations in some edge …
> fix: Update Vivliostyle.js to 2.18.2: Bug fixes on text-spacing and viewer

- package.json
- yarn.lock
https://github.com/vivliostyle/vivliostyle.js/releases/edit/v2.18.3
- [Regression] wrong text-spacing with fullwidth opening brackets near end of line ([667b219](https://github.com/vivliostyle/vivliostyle.js/commit/667b2199c59e97aa3962420d0bbab0638cc71695)), closes [1010](https://github.com/vivliostyle/vivliostyle.js/issues/1010)
> fix: Update Vivliostyle.js to 2.18.3: Bug fix on text-spacing

- package.json
- yarn.lock
https://github.com/vivliostyle/vivliostyle.js/releases/tag/v2.18.4
- CSS parser error with calc expression including parens and variables ([88c4ae0](https://github.com/vivliostyle/vivliostyle.js/commit/88c4ae00039dab743945c141fcb5c167580ddf2a)), closes [1014](https://github.com/vivliostyle/vivliostyle.js/issues/1014)
- CSS parser error with property:calc(…) misinterpreted as selector with pseudo class ([71c39bf](https://github.com/vivliostyle/vivliostyle.js/commit/71c39bf665d6a2b668f175f8d3623184275ec23a)), closes [1020](https://github.com/vivliostyle/vivliostyle.js/issues/1020)
- percentage units in color value changed, resulting in invalid colors ([a45e861](https://github.com/vivliostyle/vivliostyle.js/commit/a45e861903946e3f2499f23d6ef4fe852fae30d5)), closes …
> fix: Update Vivliostyle.js to 2.18.4: Bug Fixes

- package.json
- yarn.lock
https://github.com/vivliostyle/vivliostyle.js/releases/tag/v2.19.0
- Add support for :has() pseudo-class in Selectors Level 4
- Add support for :is()/:not()/:where() pseudo-classes in Selectors Level 4
- Selector `E ::pseudo` is misinterpreted as `E::pseudo`
> feat: Update Vivliostyle.js to 2.19.0: Support :is()/:not()/:where()/:has() pseudo-classes

- package.json
- yarn.lock
https://github.com/vivliostyle/vivliostyle.js/releases/tag/v2.19.1
- Error with undefined CSS variables in calc expression in shorthand property
> fix: Update Vivliostyle.js to 2.19.1: Bug Fix

- src/browser.ts
The chromium option `--enable-blink-features=LayoutNGPrinting` does not work on Chromium 107. This feature (LayoutNGPrinting) is enabled by default from Chromium 108.
- issue #347
> fix: remove no longer necessary chromium option to enable LayoutNGPrinting

- package.json
- yarn.lock
- `@supports selector(…)` did not work
- improve box edge treatment at page break and box-decoration-break support
- wrong first line treatment on text-spacing:space-first and hanging-punctuation:first
- wrong page break prohibition between text and block box
> fix: Update Vivliostyle.js to 2.192.2: Bug Fixes

- package.json
- yarn.lock
https://github.com/vivliostyle/vivliostyle.js/releases/tag/v2.20.0
- Add support for CSS lh and rlh units
- Add support for CSS margin-break property
- Support (-webkit-)text-stroke properties
- hanging-punctuation makes text selection difficult for paragraph-last punctuation
- Question: react renderer size
- Some text-* properties are not applied to page margin box content
- Text-decoration-line should not be skipped at ideograph-alpha/numeric text spacing
- Wrong cascading with shorthand property text-decoration and its longhand
> feat: Update Vivliostyle.js to 2.20.0: CSS lh/rlh units and margin-break property support

- package.json
- yarn.lock
- https://github.com/vivliostyle/vivliostyle.js/releases/tag/v2.21.1
- https://github.com/vivliostyle/vivliostyle.js/releases/tag/v2.21.0
- Enable very thin border width on PDF output
- Update CSS text-spacing property spec to align to the latest draft
- Improve page auto spread view mode
- Top page float should not absorb margin/border/padding of the block below
- Page break position changes depending on display device pixel ratio
- `float-min-wrap-block: 0` causes "TypeError: Cannot read properties of undefined"
- break-before:column on single column causes printed page content disappear
- display and overflow property value definition
- remove workaround for old Chrome printing problem
- wrong white-space processing on non-ASCII spaces such as U+3000 IDEOGRAPHIC SPACE
> feat: Update Vivliostyle.js to 2.21.1: Enable very thin border width; Update CSS text-spacing

- package.json
- yarn.lock
- https://github.com/vivliostyle/vivliostyle.js/releases/tag/v2.22.0
- Support CSS leader() function
- very thin border on printing with Microsoft Edge
- layout problem when devicePixelRatio is changed during rendering
> feat: Update Vivliostyle.js to 2.22.0: Support CSS leader() function

- package.json
- yarn.lock
I did:
```
yarn upgrade nodemon ora shelljs serve-handler @vivliostyle/vfm release-it @release-it/conventional-changelog
yarn upgrade --latest release-it @release-it/conventional-changelog
```
----
Before this update, the result of `yarn audit` was (partial):
```
$ yarn audit
yarn audit v1.22.19
┌───────────────┬──────────────────────────────────────────────────────────────┐
│ high          │ Improper Privilege Management in shelljs                     │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Package       │ shelljs                                                      │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Patched in    │ >=0.8.5                                                      │ …
```
> chore(deps): update deps to resolve audit issues

- src/preview.ts
previewコマンドでブラウザが起動したとき、これまでアドレスバーにフォーカスがある状態になっていました。
この状態だと、矢印キーでのページ移動など、Viewerの操作にキーボードを利用しようとしても、うまくいきません。いったんページ内にフォーカスを移動するのにクリックする必要があって面倒でした。
また、入力の指定なしでpreviewを起動したときのURL入力ボックスが出るときもそこにフォーカスがあってすぐに入力できればいいのにそうなってませんでした。
この問題を修正しました。
> fix: browser address bar should not be focused when starting preview

- package.json
- yarn.lock
https://github.com/vivliostyle/vivliostyle.js/releases/tag/v2.22.4
- HTML `<link rel="stylesheet">` tag without href causes TypeError
- improve margin-break handling
- margin-break:discard not working properly
- no break opportunity at empty block box
- no break opportunity between anonymous block box and block-level box
- wrong cascading with CSS logical properties
- wrong page break inside table in vertical writing mode
> fix: Update Vivliostyle.js to 2.22.4: Bug Fixes

- package.json
- yarn.lock
The Chromium version installed with Playwright v1.31.0 had a bug that shows extra cmd windows in headless mode on Windows.
- https://github.com/microsoft/playwright/issues/21093
I tested `vivliostyle build` command on Windows and reproduced this problem. See screenshot:
[Playwright v1.31.1](https://github.com/microsoft/playwright/releases/tag/v1.31.1) resolves this problem:
> https://github.com/microsoft/playwright/issues/21093 - [Regression v1.31] Headless Windows shows cascading cmd windows
> fix: Update Playwright to 1.31.1 (Chromium 111.0.5563.19, bugfixed on Windows)

- package.json
- yarn.lock
https://github.com/vivliostyle/vivliostyle.js/releases/tag/v2.23.0
- Add support for new syntax of CSS text-spacing properties
- CSS rem unit not evaluated correctly in min/max/clamp functions
- SVG rendering error with `<use xlink:href=… />`
- tweak TOC detection for VFM v2 change
- Using a CSS target-counter breaks named-pages styling
- **viewer:** [Regression v2.22.4] Viewer TOC item indent too large
> feat: Update Vivliostyle.js to 2.23.0: New syntax of CSS text-spacing properties

- README.md
- src/commands/build.parser.ts
- src/commands/preview.parser.ts
- src/config.ts
READMEや--helpでの `--size` オプションの説明に "[Letter]" とありますが、これは正しくないので "[Letter]" の記述を削除しました。
`parsePageSize()` に `format: width ?? 'Letter'` というコードがありましたが、実際は `width` が null や undefined でここに来ることはなくて、この 'Letter' が使われることはありません。
実際の初期値は設定なしです。スタイルシートでpage sizeが指定されていればそのサイズになります。
もしどこにもページサイズの設定がなければ、CSSでのpage sizeの初期値であるautoです。その場合、preview表示ではブラウザのウインドウサイズで決まるページサイズになり、buildでのPDF出力では適当なページサイズになります（その適当なページサイズについて詳しくは： https://github.com/vivliostyle/vivliostyle.js/pull/876 ）。
> docs: page size initial value "Letter" is not correct

- package.json
- yarn.lock
https://github.com/vivliostyle/vivliostyle.js/releases/tag/v2.23.1
- Leader layout problem dependent on font and language
- Page background image is not painted in the bleed area
> fix: Update Vivliostyle.js to 2.23.1: Bug Fixes

- package.json
- yarn.lock
https://github.com/vivliostyle/vivliostyle.js/releases/tag/v2.23.2
- Page content is not painted in the bleed area (Regression in v2.23.1)
> fix: Update Vivliostyle.js to 2.23.2: Bug Fix (Regression)

- src/preview.ts
Vivliostyle Viewer (>=2.24) has UI language setting, which uses browser's language (navigator.language) by default. However Vivliostyle CLI sets `--lang=en` to the browser to avoid language-depended problem, so we cannot rely on browser language.
This commit solves this problem.
> feat: set UI language of Vivliostyle Viewer

- README.md
- src/commands/build.parser.ts
- src/commands/build.ts
- src/commands/preview.parser.ts
- src/commands/preview.ts
- src/config.ts
- src/pdf.ts
- src/preview.ts
- src/schema/vivliostyleConfig.schema.ts
- src/server.ts
- tests/__snapshots__/config.test.ts.snap
- tests/config.test.ts
- tests/fixtures/config/vivliostyle.config.valid.1.cjs
- tests/server.test.ts
- resolves #169
preview and build option:
--viewer-param <parameters>     specify viewer parameters. (ex: "allowScripts=false&pixelRatio=16")
config property:
/**
* specify viewer parameters. (ex: "allowScripts=false&pixelRatio=16")
*/
viewerParam?: string;
The specified viewer parameters are appended to the viewer URL parameters.
> feat: Viewer parameter setting: `--viewer-param` option (viewerParam property)

- package.json
- yarn.lock
https://github.com/vivliostyle/vivliostyle.js/releases/tag/v2.24.1
- fix: wrong message "[object Object]" instead of delete confirmation
> fix: Update Vivliostyle.js to 2.24.1: Bug Fix

- src/preview.ts
Viewerの新機能であるマーカー注釈機能で、マーカー・注釈を削除するときの確認メッセージのダイアログが自動的にキャンセルされてしまう問題を修正します。
関連PR：
- https://github.com/vivliostyle/vivliostyle-cli/pull/391#issuecomment-1492892872
> CLIではこのままではその確認メッセージも出ない問題があることに気がつきました。原因はPlaywrightがデフォルトでconfirm()を閉じてしまうようにしてることのようです。
>
> https://playwright.dev/docs/next/dialogs
>
> > alert(), confirm(), prompt() dialogs
> >
> > By default, dialogs are auto-dismissed by Playwright,...
> fix: prevent confirm dialog from being auto-dismissed

- package.json
- yarn.lock
https://github.com/vivliostyle/vivliostyle.js/releases/tag/v2.25.0
- Add support for CSS running elements
- content(first-letter) in string-set property should respect ::before/after pseudo-elements
- image size in page margin boxes
- some list style types are unavailable in list-style shorthand property
- text-spacing:none for pre/code/kbd/samp/tt elements should be default
- unnecessary forced page breaks at the beginning of page after out-of-flow elements
- **viewer:** prevent wrong text selection touching page navigation buttons
- Vivliostyle crashes when using CSS namespaces
- Vivliostyle crashes with "Error: Function xxx is undefined"
- Vivliostyle crashes with "Error: Internal error"
- widows and orphans properties are ignored inside multi-column box
- wrong layout with …
> feat: Update Vivliostyle.js to 2.25.0: Support CSS Running Elements

- .github/workflows/test.yml
- package.json
- yarn.lock
- [feat: Update Playwright to 1.34.3 (Chromium 114.0.5735.26)](https://github.com/vivliostyle/vivliostyle-cli/commit/8dde8317e7bd3fb208077cb96477880999ae3560)
- [chore: change playwright to playwright-core in pretest script](https://github.com/vivliostyle/vivliostyle-cli/commit/eeb30c982bee654e507cabdf3df14e2d57f1a650)
> This change is necessary because of the change in playwright v1.34.3.
> see https://github.com/microsoft/playwright/pull/23260
- [chore: change playwright to playwright-core in test.yml](https://github.com/vivliostyle/vivliostyle-cli/pull/409/commits/87349d66dc3c88e14d395248731e0563fa2ee20d)
> feat: Update Playwright to 1.34.3 (Chromium 114.0.5735.26)

- src/browser.ts
- fix #399
Chromiumの言語設定が日本語や中国語など特定の言語の場合に最小フォントサイズ10pxあるいは12pxの制限が生じる問題に対して、Chromiumのコマンドラインオプションで言語設定を強制的に英語になるようにして対処してましたが、macOSではそれが機能してませんでした。
macOSの場合には、`-AppleLanguages '(en)'` を指定することで言語設定を英語に切り替えて起動することができることが分かったので、そのようにしてみました。--headless と同時に指定するとエラーになるので `!headless && process.platform === 'darwin'` の条件のときにこの指定をするようにしました（headlessの場合には常に英語になるのでこれで問題はない）。
> fix: preview minimum font-size problem depending on locale on macOS

- package.json
- yarn.lock
https://github.com/vivliostyle/vivliostyle.js/releases/tag/v2.25.3
- EPUB font deobfuscation not working
- Failed to load when publication manifest has stylesheet URL without extension
- Numbered list counts go wrong when footnote-related pseudo-elements exist
- viewer: Unexpected scrollbar appears when loading W3C documents
- wrong URL resolution when baseURL has no file name extension
> fix: Update Vivliostyle.js to 2.25.3: Bug Fixes

- package.json
- yarn.lock
https://github.com/vivliostyle/vivliostyle.js/releases/tag/v2.25.5
- negative page margin values not working as expected
- TOC box disappeared when resizing window
> fix: Update Vivliostyle.js to 2.25.5: Bug Fixes

- tests/builder.test.ts
This update is necessary because the remote theme file names have been changed in the latest version of vivliostyle themes.
> test: update remote theme tests

- package.json
- yarn.lock
https://github.com/vivliostyle/vivliostyle.js/releases/tag/v2.25.6
- viewer: Current page should be kept after Find results in "Not Found"
- viewer: Exclude generated page margin box content from text search
- viewer: Navigation with page slider should not affect browser history stack
- viewer: selection highlighting problems on iOS
- viewer: tweak viewer UI for mobile devices
- viewer: tweak viewer UI style for mobile devices
> fix: Update Vivliostyle.js to 2.25.6: Viewer UI Bug Fixes

- src/processor/html.ts
Added this attribute because CSS was not applied correctly without it on e-reader devices (Checked on Kindle paperwhite 11th).
マークダウンからKindle Paperwhite 11thで日本語縦書きに対応したEPUB出力を試していて気付いたのですが。
vivliostyle.config.jsに”readingProgression: 'rtl',”のオプションを追加するとCSSが正常に読み込まれず、右開き縦書きのはずが左開き横書きEPUBとなり、縦書きが適用されなくなりました。不思議なことに他は何も変更せず、このオプションを削除すると左開き縦書きEPUBとなります。
ネットで取得した、正常に右開き縦書き表示できるEPUBとVivliostyle-cliで出力した右開き縦書き（端末で見ると横書き）のEPUBと比較して判明したのが”type="text.css"の有無でした。
CLIだけ問題かと思ってソースを辿っていくとマークダウンからの出力の場合はVFMも影響していましたので[こちら](https://github.com/vivliostyle/vfm/pull/173)も修正しました。
Kindle Paperwhite 11thにも対応してほしいので、レビューよろしくお願いします。
サンプルに修正前（無印）と後（FIX)で出力したEPUBも添付しておきます。どちらもViewerでは縦書きですが、端末でみると無印は横書きになってしまいます。
[ProgressionRTL_FIX.epub.zip](https://github.com/vivliostyle/vivliostyle-cli/files/12872882/Progressio …
> Added Type attribute to Link of CSS

- package.json
- yarn.lock
https://github.com/vivliostyle/vfm/releases/tag/v2.2.0
- Support non-sectionize headings, enclosed by equal number of hashes
- Support section-end mark (line with only hashes)
- HTML block with markdown heading causes wrong HTML sectioning
- HTML title generated from heading should not have ruby text and HTML tags
- Added Type attribute to Link of CSS
> feat: Update VFM to 2.2.0: New features to control sectionization

- package.json
- yarn.lock
https://github.com/vivliostyle/vivliostyle.js/releases/tag/v2.25.8
- page breaking inside table may cause unexpected page type reset
> fix: Update Vivliostyle.js to 2.25.8: Bug Fix

- package.json
- yarn.lock
https://github.com/vivliostyle/vivliostyle.js/releases/tag/v2.26.0
- Update CSS text-spacing-trim property to support the latest spec change
- set hanging-punctuation:none for pre-formatted text default style
- text-spacing-trim not working properly in some cases
> feat: Update Vivliostyle.js to 2.26.0: Update CSS text-spacing support

- package.json
- yarn.lock
https://github.com/vivliostyle/vivliostyle.js/releases/tag/v2.27.0
- Update CSS user agent default style sheet
- HTML documents listed in "resources" in pub-manifest should not be rendered as if in "readingOrder"
- remove ruby font-size workaround no longer necessary
- text-spacing not working properly with text-spacing natively enabled browser
- text-spacing-trim:space-first not working properly in some case
- TOC box should contain only the TOC element content
- Units vi and vb are mishandled when writing-mode is different from the root element
- vertical-in-horizontal block height and horizontal-in-vertical block width not computed properly
- Viewer page navigation hangs with EPUB/webpub with undetermined page-progression-direction
> feat: Update Vivliostyle.js to 2.27.0: Default stylesheet update and bug fixes

- src/const.ts
- src/output/epub.ts
- tests/__snapshots__/epub.test.ts.snap
- tests/epub.test.ts
#469
* Disable insertion of the generated nav elements if `nav[epub:type]` exists in the original document.
* Changed so that `<nav epub:type="toc">` is inserted before `<nav epub:type="landmarks">`.
* Added headings within each `<nav epub:type="...">` element. ex: `<h2>Table of Contents</h2>`, `<h2>Landmarks</h2>`
> fix: Improve EPUB nav elements

- package.json
- yarn.lock
https://github.com/vivliostyle/vivliostyle.js/releases/tag/v2.28.0
- adjust TOC box width to account for scrollbar width
- All `<nav epub:type="…">` elements in EPUB navigation doc should be shown in TOC box
- blank page selector misapplied when target-counter is used
- break-before specified on floats may not work
- Column floats disappear
- Float box pushed out of the page area
- float margins collapsed wrongly
- remove old EPUB NCX handling
- set overflow property of `@-epubx-partition` to hidden by default
- target-counter leads to pagination to wrong named page
- Top margin at unforced page break not truncated correctly
- Top margin of floats at page start should be kept
- TypeError occurs on repeating_elements/nesting test
- Add errorCallback config option to …
> feat: Update Vivliostyle.js to 2.28.0: Bug fixes and error handling

- src/output/epub.ts
- tests/__snapshots__/epub.test.ts.snap
- tests/epub.test.ts
https://github.com/vivliostyle/vivliostyle-cli/pull/470#issuecomment-1956354238
* Drop support exporting a legacy NCX document
* Drop support setting a legacy `guide` element in EPUB OPF
> fix: Drop legacy feature for EPUB 2

- src/init.ts
- src/util.ts
fix #479
Windows上でpreviewをCtrl+Cで終了させたとき、`runExitHandler()` が呼ばれない（そのためChromiumのプロセスが残る、また、一時ファイルが削除されない）不具合を修正しました。
previewだけでなくbuildの場合でも後処理がされない不具合は同じでした（一時ファイルが削除されない）。
問題はWindowsではsignal eventsがサポートされず、`process.on('SIGINT', …)` が機能しないことだったので、代わりにreadline interfaceを使うようにしました。
参考: https://stackoverflow.com/questions/10021373/what-is-the-windows-equivalent-of-process-onsigint-in-node-js
また、`process.on(sig, () => { … }` で、`sig !== 'exit'` の場合だけ `process.exit(1)` を呼ぶようにしました。そうしないとChromiumが残ってしまう問題が解消しなかったためです。問題あるでしょうか？
> fix: Chromium processes and tmp files remain after preview/build exit with Ctrl+C on Windows

- package.json
- yarn.lock
https://github.com/vivliostyle/vivliostyle.js/releases/tag/v2.29.0
- Named page wrongly applied to blank pages
- layout precision problem on float boxes
- Wrong handling of shorthand properties with variables in conditional rules
- Unnecessary page break at footnote or page bottom float
- CSS font descriptors wrongly validated as font properties
- text-spacing-trim may not work properly between different font sizes
- Update CSS text-spacing-trim support: Rename trim-auto to trim-both
> feat: Update Vivliostyle.js to 2.29.0: Update CSS text-spacing support

- package.json
- yarn.lock
https://github.com/vivliostyle/vivliostyle.js/releases/tag/v2.30.0
- Images with percentage height cause page overflow
- Images with width and height specified causes page overflow
- Images with width and height specified may dissapear in print
- internal use of `class="table-cell-container"` may conflict with author/user's use
- Page breaks not made between some inline elements such as images
- running element page counter incorrect
- table pagination problem
- The windows environment failed to yarn dev
- TypeError occurs when `:has(+ …)` is used with universal or root selector
- **viewer:** UI Chinese language support (zh-Hans, zh-Hant)
> feat: Update Vivliostyle.js to 2.30.0: Chinese UI, Pagination bugfix, and more

- package.json
- yarn.lock
https://github.com/vivliostyle/vivliostyle.js/releases/tag/v2.30.1
- InvalidNodeTypeError may happen during table pagination (Regression in v2.30.0)
> fix: Update Vivliostyle.js to 2.30.1: Bug Fix

- package.json
- yarn.lock
https://github.com/vivliostyle/vivliostyle.js/releases/tag/v2.30.2
- `-adapt-template: footnote` should work for "user-agent.xml#footnote"
- `epub:type="footnote"` on non-`aside` element should not cause footnote layout
- Attribute selectors with wildcard namespace not worked
- Browser-native MathML should be enabled when MathJax is not loaded
- Flexbox not working on page floats (Regression in v2.28.0)
- unsupported nested media rule causes subsequent rules to fail
> fix: Update Vivliostyle.js to 2.30.2: Bug Fixes

- package.json
- yarn.lock
Note: The Chromium version found in the [Playwright v1.45.2 release note](https://github.com/microsoft/playwright/releases/tag/v1.45.2) is 127.0.6533.5 but I found that the actual version is 127.0.6533.17.
> feat: Update Playwright to 1.45.2 (Chromium 127.0.6533.17)

- package.json
- yarn.lock
https://github.com/vivliostyle/vivliostyle.js/releases/tag/v2.30.4
- Chromium's standard CSS zoom support check
> fix: Update Vivliostyle.js to 2.30.4: Bug fix

- src/preview.ts
fix: #515 
`Locator.focus`に`timeout`を明示的に指定することで、ビルドにどれほど時間がかかるHTMLもプレビューできます。動作確認用のHTMLが必要であればIssueに添付したスクリプトから生成してください。
1点要確認事項があります。Playwrightでは[`timeout`の既定値は`0 - no timeout`](https://github.com/microsoft/playwright/blob/11014145ce37a8d44b6083fcf2c5f71453f018c7/packages/playwright-core/types/types.d.ts#L13072-L13080)とされており本PRの変更は不要なはずですが、少なくとも私の手元では挙動が変わります。他箇所での`browserContext.setDefaultTimeout`あるいは`page.setDefaultTimeout`の変更が影響しているか、Playwright側の不具合かもしれません。
> fix: Set timeout to Locator.focus

- package.json
- yarn.lock
https://github.com/vivliostyle/vivliostyle.js/releases/tag/v2.30.5
- Wrong processing order of counter-set and counter-increment
- CSS counter-reset scoping problem
- CSS counter-increment and counter-reset should be ignored for elements with `display: none`
- CSS implicit list-item counter
- CSS direction property ignored on margin boxes
- writing-mode on `@page` not inherited properly to margin boxes
- Float box inside inline element disappeared at page break
- Prevent "A network error occurred." in console when using web fonts
- "Failed to parse stylesheet" warning (Firefox and Safari)
- **viewer:** Deprecated meta tag "apple-mobile-web-app-capable"
> fix: Update Vivliostyle.js to 2.30.5: Bug Fixes

- package.json
- yarn.lock
https://github.com/vivliostyle/vivliostyle.js/releases/tag/v2.30.6
- Broken text layout at page break when ruby-text font size is larger than usual
- Broken text layout at page/column break caused by inline SVG
- error in react/storybook
- Improve epub:noteref/footnote support
- Make Arabic letters look connected before and after break at soft hyphen
- text-autospace should not put space glyph in PDF
> fix: Update Vivliostyle.js to 2.30.6: Bug Fixes

- src/processor/markdown.ts
#541
- 将来的にはVFM以外のメタデータを取得する拡張も検討の余地があるため、`DocumentProcessorFactory`のインターフェイスは変更せず、単にエラーを握り潰し空のオブジェクトを返しています。
- エラーを握り潰すのは自明ではないと判断しコメントを追加しています。
> Add fallback for metadata extraction

- .github/workflows/test.yml
- package.json
- src/browser.ts
See #545
fix #546 
* chore: Force to set devicePixelRatio=1 in headless Chrome 9c20ad2a9d95ba07e71b06f3ace490b2a259b793
* fix: Fix to work --browser option 0d68f0e04a68a7ed68da6a0d2247ac74cecf22fc
> Fix issues of Playwright 1.49.0

- .github/workflows/test.yml
- package.json
- src/browser.ts
- yarn.lock
- feat: Update Playwright to 1.49.0 (Chromium 131.0.6778.33) (eadf6da)
- fix: Use chromium-headless-shell rather than chromium in new headless mode (44737f3)
In [Playwright v1.49.0](https://github.com/microsoft/playwright/releases/tag/v1.49.0), new Chromium headless mode is introduced, and old headless mode is separated as "chromium-headless-shell".
Unfortunately, the new headless mode has a problem (see Issue #357), so we need to use "chromium-headless-shell".
> feat: Update Playwright to 1.49.0 (Chromium 131.0.6778.33)

- package.json
- yarn.lock
https://github.com/vivliostyle/vivliostyle.js/releases/tag/v2.30.7
- Float box may appear twice at page break (Regression in v2.30.5)
- prevent breaking inside SVG
- prevent wrong break at beginning of paragraph
> fix: Update Vivliostyle.js to 2.30.7: Layout bug fixes

- package.json
- yarn.lock
https://github.com/vivliostyle/vivliostyle.js/releases/tag/v2.30.8
- fix broken table layout when table row has id attribute
- fix calc() not working for unitless values
- fix named page not applied at first page with running element
- fix wrong cascading with -webkit-box-sizing and box-sizing
- prevent running elements and absolutely positioned elements from being broken
- prevent wrong page/column break at ruby
- Table cell with rowspan may disappear after page break
- Text-decoration-line should not be skipped at space inserted by text-spacing
> fix: Update Vivliostyle.js to 2.30.8: Bug Fixes

- package.json
- yarn.lock
https://github.com/vivliostyle/vivliostyle.js/releases/tag/v2.31.0
- Support extended CSS Page float values such as `float: top right`
- support logical values for CSS clear property
> feat: Update Vivliostyle.js to 2.31.0: Extended CSS Page Floats support

- package.json
- yarn.lock
https://github.com/vivliostyle/vivliostyle.js/releases/tag/v2.31.1
- Do not remove table top border with thead and bottom border with tfoot at page
- Fix `break-inside: avoid` ignored in table cells
- Fix auto spread view behavior when page size changes
- Fix incorrect column balancing in vertical writing mode
- Fix named page not applied after a spread break
> fix: Update Vivliostyle.js to 2.31.1: Bug Fixes

- src/browser.ts
- src/util.ts
fix: #565 
WSL内で実行されている場合のみ`--disable-gpu`を追加するようにしました。ただし、WSLの中で実行されていることを確実に判定する方法は存在しないようです。
WindowsとWSLで動作確認済みです。
> fix: Add --disable-gpu option when running on WSL

- src/browser.ts
> chore: Fix preview error "Arguments can not specify page to be opened" on macOS

- package.json
- yarn.lock
https://github.com/vivliostyle/vivliostyle.js/releases/tag/v2.31.2
- Error with `@-epubx-page-master { writing-mode: vertical-rl; … }`
- Fix multi-column balancing
- Fix table layout bugs on page/column break inside rowspanning cells
- Fix table layout problem with table-cells across pages
- Prevent wrong break at span with horizontal writing mode in vertical writing mode
- Replace XMLHttpRequest with fetch API
> fix: Update Vivliostyle.js to 2.31.2: Bug Fixes

- package.json
- pnpm-lock.yaml
https://github.com/vivliostyle/vivliostyle.js/releases/tag/v2.32.0
- Do not ignore prefixed CSS properties such as -webkit-line-clamp
- Fix table fragmentation problem overflowing page area
- **viewer:** Do not remove console output in vivliostyle-viewer.js
- Resolves #580
- Add crop-marks-line-color property for at-page rule
- Support CSS font descriptors: size-adjust, ascent-override, etc.
> feat: Update Vivliostyle.js to 2.32.0: Improve `@font-face` support, etc.

- src/config/resolve.ts
- tests/webbook.test.ts
fix #603
The webbook URL no longer automatically adds a trailing slash. If the remote server requires one, you may need to update your input accordingly.
```
vivliostyle build https://example.com/subpath
↓
vivliostyle build https://example.com/subpath/
```
> feat: Do not add a trailing slash to webbook URL

- package.json
- pnpm-lock.yaml
https://github.com/vivliostyle/vivliostyle.js/releases/tag/v2.32.1
- Avoid error in older browsers not supporting :has() selector
- Fix :blank page selector misapplied to next page using target-counter()
- Set print-color-adjust:exact to avoid background graphics from being removed
> fix: Update Vivliostyle.js to 2.32.1: Bug Fixes

- package.json
- pnpm-lock.yaml
https://github.com/vivliostyle/vivliostyle.js/releases/tag/v2.33.1
- Fix cascading between \*-inside/outside and \*-inline-start/end properties
> fix: Update Vivliostyle.js to 2.33.1: Bug Fixes

- package.json
- pnpm-lock.yaml
https://github.com/vivliostyle/vivliostyle.js/releases/tag/v2.34.0
- Improve CSS properties support for page context and page-margin boxes
- Support `fit-content` / `min-content` / `max-content` sizing values on page-margin boxes
- Support GitHub Gist URL with fragment as source file
- Fix incorrect positioning in page area with page padding
- Fix page-margin box image size with `box-sizing: border-box`
- Fix page-margin boxes overlapping issue when center width is auto and left or right one is fixed
> feat: Update Vivliostyle.js to 2.34.0: Improve CSS page-margin boxes support

- package.json
- pnpm-lock.yaml
https://github.com/vivliostyle/vfm/releases/tag/v2.3.0
- fix: Raw HTML のサンプル HTML を最新の Section 仕様に修正
- docs: improve sectionization example
- docs: deprecate aria-labelledby output
- feat: Node バージョンを 22 LTS へ移行
- feat: ESM 対応を容易にするため、テストを Jest から Vitest へ移行
- feat: プロジェクトを ESM 化
- feat: hast関連のバージョンを可能な限り上げる
- feat: mdast関連のバージョンを可能な限り上げる
- feat: unist関連のバージョンを可能な限り上げる
- fix: Remove type stubs
- feat: Update dependencies
- feat: update deps
- feat: update the release-it
> feat: Update VFM to 2.3.0: ESM support

- .github/workflows/release.yml
- .release-it.json
Reference
- https://github.blog/changelog/2025-07-31-npm-trusted-publishing-with-oidc-is-generally-available/
- https://github.com/release-it/release-it/blob/main/docs/npm.md#trusted-publishing-oidc
> ci: Add a release workflow
