vivliostyle/vivliostyle-cli

broker/main.js, package.json, src/lib/misc.ts, src/lib/preview.ts, src/lib/save.ts, yarn.lock
=> Support EPUB & XHTML

.editorconfig, Dockerfile, README.md, broker/main.js, package.json, src/cli.ts, src/lib/preview.ts, src/lib/save.ts, tests/cli.test.ts
BREAKING CHANGE: command has been changed from savepdf to vivliostyle
Refs: vivliostyle/vivliostyle#620
=> chore: rename vivliostyle-savepdf to @vivliostyle/cli

src/cli-build.ts, src/cli-preview.ts, src/lib/build.ts, src/lib/misc.ts, src/lib/preview.ts
catch unhandled promise rejection
=> fix: better error handling

package.json, src/index.ts, src/lib/build.ts
- Expose Node API
```js
const {build, preview} = require('@vivliostyle/cli')
```
=> feat: expose Node API

.github/CODEOWNERS
add CODEOWNER to automate review process
=> chore: add CODEOWNER to automate review process

broker/main.js, src/lib/build.ts
=> Fix size specifying on build command

src/lib/server.ts
`require.resolve` does not correctly locate the modules when ESM modules are enabled or when the dependencies are not located in the `node_modules/` folder of `vivliostyle-cli` itself (for instance, when `vivliostyle-cli` is used as a dependency and the package manager hoists dependencies into the root of a module).
=> Fixes broker module lookup when used as a dependency

README.md, src/cli-build.ts, src/lib/build.ts
This pull request adds `--verbose` option, which allows us to show browser consoles during Vivliostyle rendering. Thanks to a great feature, @uetchy !
=> Add --verbose option

src/builder.ts
=> fix: Local theme package copied to wrong place when updated during preview

src/config.ts, src/util.ts
=> fix: Fix judging method to detect entry file type

broker/style.css
fix #70 #71
This PR improves the CSS of broker UI to make elements rendered by Vivliostyle.js selectable.
=> Make element selectable on broker UI

package.json, src/builder.ts, src/html.ts, tests/builder.test.ts, tests/fixtures/builder/variousManuscriptFormat.config.js, yarn.lock
=> Fix to reflect language settings to manuscript outputs

src/builder.ts, src/config.ts, src/html.ts, tests/__snapshots__/config.test.ts.snap, tests/builder.test.ts
=> fix: Delete the default language config

README.md, src/commands/build.parser.ts, src/commands/init.parser.ts, src/commands/preview.parser.ts, tests/config.test.ts, tests/init.test.ts
closes #60 #121 
Please see https://github.com/vivliostyle/vivliostyle-cli/blob/aca9cf3285ff4cec28dd341c34dd185ac11ef8cc/README.md for the details of the new CLI options.
=> Revise CLI options

src/config.ts, tests/__snapshots__/config.test.ts.snap, tests/config.test.ts, tests/fixtures/builder/overwriteViolation.1.config.js, tests/fixtures/builder/overwriteViolation.2.config.js, tests/fixtures/config/vivliostyle.config.invalid.2.js, tests/fixtures/config/vivliostyle.config.valid.3.js
=> fix: Fix to raise errors on falsy input

src/markdown.ts, tests/builder.test.ts, tests/config.test.ts, tests/fixtures/builder/manuscript/frontmatter.md, tests/fixtures/builder/vfm.config.js, tests/fixtures/config/frontmatter.md
=> fix: VFM frontmatter not processed

src/postprocess.ts
Closes #97 
Changed document's `producer` and `creator` metadata for describing docs better and debugging.
=> feat: Improve PDF metadata (#97)

src/pdf.ts
The timeout building PDF phase was not configured. Fixes #230
=> fix: Make timeout building PDF configurable

src/pdf.ts, src/postprocess.ts
- Resolves #220
- Resolves #238
=> feat: Improve Vivliostyle.js/Chromium version info in output PDF

src/builder.ts, tests/builder.test.ts, tests/fixtures/webbooks/w3c-webpub/publication.json, tests/toc.test.ts
=> fix: Correct "title" to "name" in publication.json readingOrder

package.json, yarn.lock
https://github.com/vivliostyle/vivliostyle.js/releases/tag/v2.14.5
- text-spacing caused wrong page break
=> fix: Update Vivliostyle.js to 2.14.5: Fix text-spacing caused wrong page break

src/pdf.ts, src/preview.ts
=> fix: Failed to load document when --viewer option is specified

examples/multiple-input-and-output/.gitignore, examples/multiple-input-and-output/README.md, examples/multiple-input-and-output/src/1.html, examples/multiple-input-and-output/src/1.md, examples/multiple-input-and-output/src/2.html, examples/multiple-input-and-output/src/2.md, examples/multiple-input-and-output/vivliostyle.config.js, src/build.ts, src/config.ts, src/preview.ts, src/schema/vivliostyle/vivliostyleConfig.schema.json, src/schema/vivliostyleConfig.schema.ts, tests/__snapshots__/config.test.ts.snap, tests/builder.test.ts, tests/commandUtil.ts, tests/config.test.ts, tests/fixtures/builder/multipleEntry.config.js, tests/fixtures/config/vivliostyle.config.valid.4.js, tests/toc.test.ts
=> feat: Support multiple entries of config

src/browser.ts, src/build.ts, src/commands/build.ts, src/container.ts, src/pdf.ts, src/postprocess.ts, src/util.ts
The #269 issue was indeed fixed #271, however, I found this solution is a little too forcible. This PR fixes more radical reason that occurs in process spawn and improves logging content.
=> fix: Use appropreate teardown and logging

src/pdf.ts, src/postprocess.ts
- resolve #277
> When crop marks and bleed area are specified by https://github.com/vivliostyle/vivliostyle.js/issues/98, it is desirable that the output PDF has corresponding TrimBox and BleedBox parameters.
=> feat: Add TrimBox and BleedBox to output PDF

src/pdf.ts
=> fix: vivliostyle build hangs up at "Launching build environment"

package.json, yarn.lock
https://github.com/vivliostyle/vivliostyle.js/releases/tag/v2.15.4
- White line left on the page bottom in output PDF
=> fix: Update Vivliostyle.js to 2.15.4: Bug Fixes

package.json, yarn.lock
https://github.com/vivliostyle/vivliostyle.js/releases/tag/v2.15.5
- Layout problem with Chrome>=102
=> fix: Update Vivliostyle.js to 2.15.5: Fix layout problem with Chrome>=102

src/build.ts
=> fix: Build not terminated when --render-mode=docker --http

src/postprocess.ts
=> fix: Unnecessary blank page added to the last in output PDF

package.json, yarn.lock
https://github.com/vivliostyle/vivliostyle.js/releases/tag/v2.17.0
- Support CSS custom properties (variables)
=> feat: Update Vivliostyle.js to 2.17.0: Supports CSS Variables

package.json, yarn.lock
https://github.com/vivliostyle/vivliostyle.js/releases/tag/v2.17.2
- Incorrect behavior of ::first-letter and ::first-line selectors
=> fix: Update Vivliostyle.js to 2.17.2: Bug Fix

src/browser.ts
=> fix: stop using Chromium's `--headless=chrome` mode that causes layout problem on HiDPI display

src/preview.ts
=> fix: preview crashes when config has `toc: true`

package.json, yarn.lock
I confirmed that this Chromium update resolves the following problem:
- https://github.com/vivliostyle/vivliostyle.js/issues/1095
=> feat: Update Playwright to 1.30.0 (Chromium 110.0.5481.38)

package.json, yarn.lock
- https://github.com/vivliostyle/vivliostyle.js/releases/tag/v2.22.2
- https://github.com/vivliostyle/vivliostyle.js/releases/tag/v2.22.1
- Leader layout broken with text-spacing processing
- Leader layout problem with text-indent
- Leader disappears in very large page
=> fix: Update Vivliostyle.js to 2.22.2: Leader layout bug fixes

package.json, yarn.lock
https://github.com/vivliostyle/vivliostyle.js/releases/tag/v2.22.3
- PDF internal links not working properly
- Inline margins on leader not working properly
- Leader layout problem on Safari
=> fix: Update Vivliostyle.js to 2.22.3: Fix PDF internal link bug

.github/workflows/cd-workflow.yml, .github/workflows/test.yml
=> chore: Update actions setting

src/browser.ts
Resolves:
- https://github.com/vivliostyle/vivliostyle.js/issues/1078
- https://github.com/vivliostyle/vivliostyle.js/issues/1091
=> fix: preview minimum font-size problem depending on locale

package.json, yarn.lock
https://github.com/vivliostyle/vfm/releases/tag/v2.1.0
* disable attributes copy to parent
* disable img attributes copy to figure element
BREAKING CHANGE: VFM v1 → v2
=> feat: Update VFM to 2.1.0

package.json, yarn.lock
https://github.com/vivliostyle/vivliostyle.js/releases/tag/v2.24.0
- **viewer:** Multilingual user interface (en/ja)
- **viewer:** Add UI Language in settings panel
- **viewer:** Add Restore View setting
- **viewer:** Marker annotation
- Browser "Back" button should work with internal link or TOC navigation
- Rendering error with SVG images in EPUB (Regression in v2.23.0)
=> feat: Update Vivliostyle.js to 2.24.0: improved Viewer features

package.json, yarn.lock
https://github.com/vivliostyle/vivliostyle.js/releases/tag/v2.24.3
- **viewer:** marker text selection problem
- z-index on page context problem (Regression in v2.23.1)
=> fix: Update Vivliostyle.js to 2.24.3: Bug Fixes

Dockerfile
=> feat: Update Ubuntu version on Docker to jammy (22.04LTS)

package.json, yarn.lock
https://github.com/vivliostyle/vivliostyle.js/releases/tag/v2.25.2
- Variable fonts not working properly
=> fix: Update Vivliostyle.js to 2.25.2: Bugfix on variable fonts

.gitignore, vendors/.gitignore
=> fix: Fix broken release of v8.1.0

package.json, yarn.lock
https://github.com/vivliostyle/vivliostyle.js/releases/tag/v2.25.4
- **viewer:** Page navigation left/right buttons disappeared in v2.25.3
=> fix: Update Vivliostyle.js to 2.25.4: Viewer bugfix

src/preview.ts
これまでVivliostyle CLIのpreviewを終了するには、ターミナルで Ctrl+C を入力する必要がありました。
これはこのようなコマンドラインツールに慣れない人たちにとっては使いづらいです。
そこで、プレビューを表示しているChromiumブラウザ上のページを閉じるとpreviewが終了するようにしてみました。
プレビュー表示を閉じるとpreviewコマンドが動き続ける意味はないので、この動作で問題ないだろうと思います。
（注意：プレビューを表示しているChromiumブラウザで別のタブやウインドウを新しく開いている場合でも最初のプレビュー表示のタブを閉じるとすべて一緒に終了します。）
=> feat: Preview should be terminated when the previewing page is closed

src/browser.ts, src/build.ts, src/container.ts, src/output/pdf-postprocess.ts, src/preview.ts, src/util.ts
=> fix: Fix logging message when the file is updated during preview

package.json, yarn.lock
https://github.com/vivliostyle/vivliostyle.js/releases/tag/v2.25.7
- Pagination result depends on viewer window width
=> fix: Update Vivliostyle.js to 2.25.7: Bug Fix

package.json, yarn.lock
https://github.com/vivliostyle/vfm/releases/tag/v2.2.1
- HTML block causes wrong sectioning (vfm 2.2.0)
=> fix: Update VFM to 2.2.1: Bug Fix

src/input/config.ts, src/output/epub.ts
=> feat: EPUB output improvement

package.json, yarn.lock
https://github.com/vivliostyle/vivliostyle.js/releases/tag/v2.28.1
- Footnote causes layout problem on page breaking
=> fix: Update Vivliostyle.js to 2.28.1: Bug Fix

src/input/config.ts, src/preview.ts
=> fix: Ensure to work reloading the config file correctly in preview mode

package.json, src/input/config.ts, src/processor/html.tsx, yarn.lock
=> fix: error: cheerio does not provide an export named default

package.json, yarn.lock
https://github.com/vivliostyle/vivliostyle.js/releases/tag/v2.30.3
- Viewer page display size is abnormally reduced and layout is broken with Chrome 128
=> fix: Update Vivliostyle.js to 2.30.3: Fix for Chromium 128

package.json, yarn.lock
=> feat: Update Playwright to 1.46.1 (Chromium 128.0.6613.18)

src/output/pdf.ts
=> fix: Fixed to generate tagged PDF

src/browser.ts
=> fix: Always disable web security to allow cross-origin requests

src/config/resolve.ts, src/config/vite.ts, src/container.ts, src/core/build.ts, src/logger.ts, src/server.ts, src/util.ts, src/vite/vite-plugin-static-serve.ts, tests/__snapshots__/config.test.ts.snap, tests/__snapshots__/webbook.test.ts.snap, tests/command-util.ts, tests/config.test.ts, tests/webbook.test.ts, tsup.config.ts
=> Fix issues

README.md, docs/config.md, src/commands/build.parser.ts, src/config/resolve.ts, src/config/schema.ts
=> Allow --timeout 0 argument for build command and increase the default timeout to 300s

Dockerfile, docs/config.md, package.json, pnpm-lock.yaml, src/commands/build.ts, src/config/resolve.ts, src/config/schema.ts, src/container.ts, src/core/build.ts, src/logger.ts, tests/__snapshots__/config.test.ts.snap, types/command-exists.d.ts
=> fix: Docker

src/config/resolve.ts, src/config/schema.ts, src/output/webbook.ts, src/processor/html.tsx, tests/__snapshots__/webbook.test.ts.snap, tests/config.test.ts, tests/webbook.test.ts
=> fix: Restore support for file and data URL input

src/config/resolve.ts, src/output/webbook.ts, src/processor/compile.ts, src/server.ts, tests/__snapshots__/config.test.ts.snap, tests/config.test.ts
=> fix: Fix to work `--style`/`--user-style` option

package.json, pnpm-lock.yaml
https://github.com/vivliostyle/vivliostyle.js/releases/tag/v2.33.2
- Fix margin-inline-start/end on at-page not working (Regression in v2.33.1)
=> fix: Update Vivliostyle.js to 2.33.2: Bug Fix

docs/api-javascript.md, src/config/schema.ts, src/core/build.ts, src/output/webbook.ts
- fix: Remove unnecessary debugger statement a9cdceb
- feat: Add disableServerStartup option 2ee04d8
=> Minor updates

src/processor/html.tsx, tests/__snapshots__/builder.test.ts.snap, tests/__snapshots__/toc.test.ts.snap
=> fix: Work pageCounterReset option with Vivliostyle Themes

src/util.ts, src/vite/vite-plugin-dev-server.ts
=> fix: Throttle dev server reloading
